version: '3'

services:
    db:
         image: postgres

    web:
          build: .
          # image: httpd
          volumes:
            - .:/usr/src/app
          ports:
            - "8000:8000"
          